name: Event_pred

on:
  push:
    tags:
      - '*'
env:
  LAMBDA_FUNCTION_NAME: Event_pred
  AWS_REGION: us-east-2

jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        working-directory: ./event_predictor_lambda
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: zip up directory
        run: |
          cd event_predictor_lambda
          source venv/bin/activate
          cp -r $(python -c "import site; print(site.getsitepackages()[0])")/* .
          rm -r venv
          cd ..
          zip -qq -r event_predictor_lambda.zip event_predictor_lambda

      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name:  ${{ env.LAMBDA_FUNCTION_NAME }}
          zip_file: ./event_predictor_lambda.zip
          handler: main.lambda_handler
